version: '3.8'

services:
  node_app:
    image: node:20
    container_name: nudge_query_gen_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Mount the current directory to /app in the container
    working_dir: /app
    depends_on:
      - postgres
      - mongo
    command: sh -c "npm install && npm run start"

  postgres:
    image: postgres:latest
    container_name: nudge_query_gen_db
    environment:
      POSTGRES_USER: nudge_user
      POSTGRES_PASSWORD: nudge_password
      POSTGRES_DB: nudge_db
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    container_name: nudge_query_gen_mongo
    ports:
      - "27018:27017"
